/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpack;

import appservice.UserService;
import dao.GradeDAO;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Grade;

/**
 *
 * @author Admin
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    DefaultTableModel model;
    UserService service;
    int currentIndex = -1;

    public UserFrame() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Quản Lý Điểm Sinh Viên");
        this.setIconImage(new ImageIcon("D:\\Java_source\\Lab_Java_3\\Assignment\\src\\imgicon\\dashboard.png").getImage());
        model = new DefaultTableModel();
        service = new UserService();
        changeColumnName();
        fillTable(service.getGradeLists());
        displayTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchBorderLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        codeStuLabel = new javax.swing.JLabel();
        codeStuInput = new javax.swing.JTextField();
        engLabel = new javax.swing.JLabel();
        engInput = new javax.swing.JTextField();
        itLabel = new javax.swing.JLabel();
        itInput = new javax.swing.JTextField();
        avgScroreLabel = new javax.swing.JLabel();
        avgScroreDisplay = new javax.swing.JLabel();
        sportInput = new javax.swing.JTextField();
        sportLabel = new javax.swing.JLabel();
        codeErr = new javax.swing.JLabel();
        engError = new javax.swing.JLabel();
        itErr = new javax.swing.JLabel();
        sportErr = new javax.swing.JLabel();
        newBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        firsrBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        preBtn = new javax.swing.JButton();
        lastBtn = new javax.swing.JButton();
        currentIndexGrade = new javax.swing.JLabel();
        sortBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        programLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        programLabel.setText("Quản Lý Điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        searchLabel.setText("MSSV");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        searchBorderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBorderLabel.setText("Tìm Kiếm");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setText("Họ Tên Sinh Viên");

        codeStuLabel.setText("MSSV");

        engLabel.setText("Tiếng Anh");

        itLabel.setText("Tin Học");
        itLabel.setToolTipText("");

        avgScroreLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        avgScroreLabel.setText("Điểm TB");

        avgScroreDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        avgScroreDisplay.setForeground(new java.awt.Color(51, 51, 255));

        sportLabel.setText("GDTC");

        codeErr.setForeground(new java.awt.Color(255, 0, 51));

        engError.setForeground(new java.awt.Color(255, 0, 51));

        itErr.setForeground(new java.awt.Color(255, 0, 51));

        sportErr.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codeStuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codeStuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(codeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(engLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(engInput, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(engError, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(avgScroreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(avgScroreDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(itLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itInput, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(itErr, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(sportErr, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avgScroreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codeStuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeStuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addComponent(codeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avgScroreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(engInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(engError, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itErr, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(sportErr, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        newBtn.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        newBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/add-button_1.png"))); // NOI18N
        newBtn.setText("NEW");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/save_1.png"))); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/remove_1.png"))); // NOI18N
        delBtn.setText("DELETE");

        updateBtn.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/update_1.png"))); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        displayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displayTable);

        firsrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/previous-track_butt.png"))); // NOI18N
        firsrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firsrBtnActionPerformed(evt);
            }
        });

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/next_butt.png"))); // NOI18N
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        preBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/back_butt.png"))); // NOI18N
        preBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preBtnActionPerformed(evt);
            }
        });

        lastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgicon/next-track_butt.png"))); // NOI18N
        lastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastBtnActionPerformed(evt);
            }
        });

        currentIndexGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentIndexGrade.setText("Record");

        sortBtn.setText("Sắp Xếp");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBorderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sortBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(71, 71, 71))))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(firsrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(preBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lastBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(currentIndexGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(programLabel)
                        .addGap(343, 343, 343))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(programLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBorderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sortBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentIndexGrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(preBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(firsrBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (searchInput.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Nhập Vào Mã Sinh Viên");
        } else {
            ArrayList<Grade> listSearchFound = service.searchFunction(searchInput.getText());
            if (listSearchFound.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không Có Sinh Viên Nào");
            } else {
                fillTable(listSearchFound);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        clearForm();
    }//GEN-LAST:event_newBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Grade grNew = inputValidation();

        if (grNew != null) {
            for (Grade grade : service.getGradeLists()) {
                if (grade.getId().equalsIgnoreCase(grNew.getId())) {
                    JOptionPane.showMessageDialog(this, "ID Sinh Viên Đã Tồn Tại (Chỉ thể Sửa Hoặc Xóa)");
                    return;
                }
            }
            service.addFunction(grNew);
            fillTable(service.getGradeLists());
            JOptionPane.showMessageDialog(this, "Nhập Điểm Thành Công");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int rowSel = displayTable.getSelectedRow();
        if (rowSel != -1) {
            Grade grCheck = inputValidation();
            Grade grUpdate = service.getGradeLists().get(rowSel);
            if (grCheck != null) {

            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Vào Sinh Viên Cần Sửa Điểm");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void displayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayTableMouseClicked
        int rowSel = displayTable.getSelectedRow();
        codeStuInput.setEditable(false);

        if (rowSel != -1) {
            currentIndex = rowSel;
            showCurrentChoice(currentIndex);
        }

    }//GEN-LAST:event_displayTableMouseClicked

    private void preBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preBtnActionPerformed
        try {
            if (service.getGradeLists().isEmpty()) {
                throw new Exception("Chưa Có Sinh Viên Nào");
            }
            currentIndex--;
            if (currentIndex < 0) {
                currentIndex = service.getGradeLists().size() - 1;
            }

            showCurrentChoice(currentIndex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_preBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        try {
            if (service.getGradeLists().isEmpty()) {
                throw new Exception("Chưa Có Sinh Viên Nào");
            }
            currentIndex++;
            if (currentIndex >= service.getGradeLists().size()) {
                currentIndex = 0;
            }
            showCurrentChoice(currentIndex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void firsrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firsrBtnActionPerformed

        try {
            if (service.getGradeLists().isEmpty()) {
                throw new Exception("Chưa Có Sinh Viên Nào");
            }

            currentIndex = 0;
            showCurrentChoice(currentIndex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_firsrBtnActionPerformed

    private void lastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastBtnActionPerformed
        try {
            if (service.getGradeLists().isEmpty()) {
                throw new Exception("Chưa Có Sinh Viên Nào");
            }
            currentIndex = service.getGradeLists().size() - 1;
            showCurrentChoice(currentIndex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_lastBtnActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        //sort by avg score
//        Collections.sort(listGrades, (Grade o1, Grade o2) -> o1.getAvgScore() > o2.getAvgScore() ? 1 : -1);
//        model.setRowCount(0);
//        for (Grade grade : listGrades) {
//            Object[] row = {grade.getStudentCode(), grade.getEngScore(), grade.getItScore(), grade.getSportScore(), grade.getAvgScore()};
//            model.addRow(row);
//        }
    }//GEN-LAST:event_sortBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgScroreDisplay;
    private javax.swing.JLabel avgScroreLabel;
    private javax.swing.JLabel codeErr;
    private javax.swing.JTextField codeStuInput;
    private javax.swing.JLabel codeStuLabel;
    private javax.swing.JLabel currentIndexGrade;
    private javax.swing.JButton delBtn;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel engError;
    private javax.swing.JTextField engInput;
    private javax.swing.JLabel engLabel;
    private javax.swing.JButton firsrBtn;
    private javax.swing.JLabel itErr;
    private javax.swing.JTextField itInput;
    private javax.swing.JLabel itLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastBtn;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton preBtn;
    private javax.swing.JLabel programLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel searchBorderLabel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton sortBtn;
    private javax.swing.JLabel sportErr;
    private javax.swing.JTextField sportInput;
    private javax.swing.JLabel sportLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    public void fillTable(ArrayList<Grade> displayList) {
        model.setRowCount(0);
        for (Grade grade : displayList) {
            Object[] row = {grade.getStudentCode(), grade.getEngScore(), grade.getItScore(), grade.getSportScore(), grade.getAvgScore()};
            model.addRow(row);
        }
    }

    public void changeColumnName() {
        ArrayList<String> coLumnName = GradeDAO.getInstance().getColumnNames();
        for (int i = 1; i < coLumnName.size(); i++) {
            String name = coLumnName.get(i);
            model.addColumn(name);
        }
        model.addColumn("Điểm Trung Bình");
    }

    public void showCurrentChoice(int index) {
        Grade gr = service.getGradeLists().get(index);
        String nameStu = GradeDAO.getInstance().getNameStudent(gr.getStudentCode());
        nameDisplay.setText(nameStu);
        codeStuInput.setText(gr.getStudentCode());
        codeStuInput.setEditable(false);
        engInput.setText(String.valueOf(gr.getEngScore()));
        itInput.setText(String.valueOf(gr.getItScore()));
        sportInput.setText(String.valueOf(gr.getSportScore()));
        avgScroreDisplay.setText(String.valueOf(gr.getAvgScore()));
        displayTable.setRowSelectionInterval(currentIndex, currentIndex);
        currentIndexGrade.setText("Record: " + (index + 1) + " / " + service.getGradeLists().size());
    }

    private Grade inputValidation() {
        String stucode = "";
        float engSc = 0;
        float itSc = 0;
        float sportSc = 0;
        int countErr = 0;

        if (codeStuInput.getText().isEmpty()) {
            countErr++;
            codeErr.setText("Bạn Phải Nhập Vào Mã Sinh Viên");
        } else if (!codeStuInput.getText().startsWith("PH")) {
            countErr++;
            codeErr.setText("Mã Sinh Viên Sai Cú Pháp");

        } else if (service.checkValidStudentCode(codeStuInput.getText())) {
            countErr++;
            codeErr.setText("Mã Sinh Viên Không Tồn Tại");
        } else {
            stucode = codeStuInput.getText();
            codeErr.setText("");
        }

        if (engInput.getText().isEmpty()) {
            countErr++;
            engError.setText("Bạn Phải Nhập Vào Điểm Tiếng Anh");
        } else {
            try {
                engSc = Float.parseFloat(engInput.getText());
                engError.setText("");
            } catch (NumberFormatException e) {
                countErr++;
                engError.setText("Bạn Nhập Sai Cú Pháp");
            }
        }

        if (itInput.getText().isEmpty()) {
            countErr++;
            itErr.setText("Bạn Phải Nhập Vào Điểm Tiếng Anh");
        } else {
            try {
                itSc = Float.parseFloat(itInput.getText());
                itErr.setText("");
            } catch (NumberFormatException e) {
                countErr++;
                itErr.setText("Bạn Nhập Sai Cú Pháp");
            }
        }

        if (sportInput.getText().isEmpty()) {
            countErr++;
            sportErr.setText("Bạn Phải Nhập Vào Điểm Tiếng Anh");
        } else {
            try {
                sportSc = Float.parseFloat(sportInput.getText());
                sportErr.setText("");
            } catch (NumberFormatException e) {
                countErr++;
                sportErr.setText("Bạn Nhập Sai Cú Pháp");
            }
        }

        if (countErr == 0) {
            Grade gr = new Grade(stucode, engSc, itSc, sportSc);
            Float avgScore = gr.getAvgScore();
            avgScroreDisplay.setText(String.valueOf(avgScore));
            return gr;
        }
        return null;
    }

    public void clearForm() {
        nameDisplay.setText("");
        codeStuInput.setEditable(true);
        codeStuInput.setText("");
        engInput.setText("");
        itInput.setText("");
        sportInput.setText("");
        avgScroreDisplay.setText("");
        codeErr.setText("");
        engError.setText("");
        itErr.setText("");
        sportErr.setText("");
        fillTable(service.getGradeLists());
    }
}
